### ISSUE TITLE
Session always gone after login

### ISSUE THREAD

**Issue by gierg** [mosrur/CI-NewsPortal#1]
I don't understand with your code for login mechanism, i was trying login on my page, the session is always gone.

**Comment by mosrur** [comment]
This is how it works - 
After you register an account, the user will get an email with an activation. The user has to click on the given link in email to activate the account. Afterwards, any user would be able to login using login form and the core mechanism is - 
Account Controller handles all authentication process. So, the Controller (controllers/Account.php) Account@login method after the validation (line 207 -210) checks the login process with a Helper file(helpers/user_helper.php) user_helper@is_logged_in (line 9-19) and the helper file calls the User Library (libraries/user.php) to get user Logged in. Library User@loggedIn (line 21-27) creates a session variable and returns true. 

Why I designed to going through helper file? Because that way I can connect to User library (which handles the authentication) and check the user authentication anywhere in the page view or controller. 

Hope, this explanation will help you to understand. Please, reply me with a feedback for any inconvenience. 


-
